site_name: TAG Python Starter
# Remove site_url for local development
# site_url: https://theagenticguy.github.io/tag-python-starter
# repo_url: https://github.com/theagenticguy/tag-python-starter
# edit_uri: blob/main/{path}

# Fix for local development
use_directory_urls: false

# Add this to ensure index is processed
docs_dir: docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      title: On this page
      permalink: true

extra_javascript:
  # Workaround for site_url breaking mermaid rendering; see the following for more info:
  # https://github.com/squidfunk/mkdocs-material/issues/3742#issuecomment-1076068038
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js

# ──────────────────────────────
#  Plugins (same power stack you saw in strands-agents)
# ──────────────────────────────
plugins:
  - awesome-pages # YAML front-matter nav tweaks
  - search # built-in client-side search
  - mermaid2 # ```mermaid``` blocks
  - autorefs # [[ on-the-fly links ]]
  - include-markdown # !INCLUDE snippets
  - redirects # maintain old URL aliases

# ──────────────────────────────
#  Navigation
# ──────────────────────────────
nav:
  - Home: index.md
